return {
    Memory = require("lib/Memory"),
    Timer = require("lib/Timer"),
    Yielder = require("lib/Yielder"),
    -- collections
    Grid2D = require("lib/collection/Grid2D"),
    Grid3D = require("lib/collection/Grid3D"),
    PriorityQueue = require("lib/collection/PriorityQueue"),
    Queue = require("lib/collection/Queue"),
    SortedArray = require("lib/collection/SortedArray"),
    Stack = require("lib/collection/Stack"),
    WeightedArray = require("lib/collection/WeightedArray")
}
